<template>
    <div>
        <h2 class="text-center text-3xl text-[#3f3a64] dark:text-white font-bold">Message From Paathshala Education</h2>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] py-5">We at Paathshala Education, are proud to be a team of dedicated individuals focused on being the best possible chance for any student to achieve his Science Career related dreams. For this, our team of Professors, Administration Executives, Student Welfare Counsellors, Academic Counsellors, Graphic Designers, Content Executives et cetera work tirelessly, often around the clock</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">We hope to be a part of the successful future of you and your child. We believe that success will follow us when we lead many a student into achieving his own dreams and goals in life. We try our best to motivate each young mind towards conceptualizing a career and marching towards conquering it</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">The years bygone, have seen Paathshala executives and personnel taking care of each student’s needs and welfare by going out of the way to do so.
We take this opportunity to sincerely commend their efforts. We are also obliged and very thankful to the many parents who have encouraged us from our nascence and students who have studied sincerely with us with supreme dedication</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">There are a few things that our great nation of India is proud to have and a couple of them are the IIT JEE Advanced and the Pre-medical Entrance Exams. These exams have been sacrosanct in deciding the country’s future and we are proud to be a part of the process that creates enlightened knowledgeable individuals, not just in bookish consistency but also in practical, rational, logical, imaginative thought, creative enough of dealing with new problems of the modern post industrial post technological era</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">We also nurture those talented students who may have been from a poor economic background and hence could not possibly afford an urban, technology enhanced Education that we are specialized in offering. We have proudly helped numerous such meritorious kids</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">We believe in honesty over delusion. If a child is not capable, due to any reason of cracking the entrance exams/Olympiads/ competitive exams or of performing well, we believe in stating that honestly in our Student Reports issued periodically. Parents are advised to understand that each and every kid isn’t meant for an intellectually stupefying career path, some can be more artistically inclined or in today’s day and age, may find new and alternative career routes, previously unheard of. For guiding the students aptly, we have a dedicated post exam counselling session after all the exams of the XII standard are over, which help the student in determining his/her exact goals and focus down upon them with pin point accuracy</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">Our work leaves us prideful, joyous and fulfilled and hence, here we mention it with our heads held high</p>
        <p class="px-36 text-gray-300 mx-5 text-justify dark:text-[#ddd] pb-5">We wish you the very best of success in all future endeavours, and sincerely hope to be and integral part of your smile, on result day</p>
        <p class=" px-36  text-gray-300 mx-5   dark:text-[#ddd]">Paathshala Education</p>
        <p class=" px-36 text-gray-300 mx-5  dark:text-[#ddd]">www.paathshala.world</p>
    </div>
</template>

